import { Planet } from '../Results/Results';

export const planets: Planet[] = [
  {
    name: 'bla1',
    diameter: 'bla',
    climate: 'bla',
    terrain: 'bla',
    population: 'bla',
    url: 'bla',
  },
  {
    name: 'bla2',
    diameter: 'bla',
    climate: 'bla',
    terrain: 'bla',
    population: 'bla',
    url: 'bla',
  },
  {
    name: 'bla3',
    diameter: 'bla',
    climate: 'bla',
    terrain: 'bla',
    population: 'bla',
    url: 'bla',
  },
  {
    name: 'bla4',
    diameter: 'bla',
    climate: 'bla',
    terrain: 'bla',
    population: 'bla',
    url: 'bla',
  },
  {
    name: 'bla5',
    diameter: 'bla',
    climate: 'bla',
    terrain: 'bla',
    population: 'bla',
    url: 'bla',
  },
  {
    name: 'bla6',
    diameter: 'bla',
    climate: 'bla',
    terrain: 'bla',
    population: 'bla',
    url: 'bla',
  },
  {
    name: 'bla7',
    diameter: 'bla',
    climate: 'bla',
    terrain: 'bla',
    population: 'bla',
    url: 'bla',
  },
  {
    name: 'bla8',
    diameter: 'bla',
    climate: 'bla',
    terrain: 'bla',
    population: 'bla',
    url: 'bla',
  },
  {
    name: 'bla9',
    diameter: 'bla',
    climate: 'bla',
    terrain: 'bla',
    population: 'bla',
    url: 'bla',
  },
  {
    name: 'bla10',
    diameter: 'bla',
    climate: 'bla',
    terrain: 'bla',
    population: 'bla',
    url: 'bla',
  },
];
