import { Planet } from '../Results/Results';

export const planets: Planet[] = [
  {
    name: 'bla1',
    diameter: 'bla',
    climate: 'bla',
    terrain: 'bla',
    population: 'bla',
    url: 'https://swapi.dev/api/planets/1/',
  },
  {
    name: 'bla2',
    diameter: 'bla',
    climate: 'bla',
    terrain: 'bla',
    population: 'bla',
    url: 'https://swapi.dev/api/planets/1/',
  },
  {
    name: 'bla3',
    diameter: 'bla',
    climate: 'bla',
    terrain: 'bla',
    population: 'bla',
    url: 'https://swapi.dev/api/planets/1/',
  },
  {
    name: 'bla4',
    diameter: 'bla',
    climate: 'bla',
    terrain: 'bla',
    population: 'bla',
    url: 'https://swapi.dev/api/planets/1/',
  },
  {
    name: 'bla5',
    diameter: 'bla',
    climate: 'bla',
    terrain: 'bla',
    population: 'bla',
    url: 'https://swapi.dev/api/planets/1/',
  },
  {
    name: 'bla6',
    diameter: 'bla',
    climate: 'bla',
    terrain: 'bla',
    population: 'bla',
    url: 'https://swapi.dev/api/planets/1/',
  },
  {
    name: 'bla7',
    diameter: 'bla',
    climate: 'bla',
    terrain: 'bla',
    population: 'bla',
    url: 'https://swapi.dev/api/planets/1/',
  },
  {
    name: 'bla8',
    diameter: 'bla',
    climate: 'bla',
    terrain: 'bla',
    population: 'bla',
    url: 'https://swapi.dev/api/planets/1/',
  },
  {
    name: 'bla9',
    diameter: 'bla',
    climate: 'bla',
    terrain: 'bla',
    population: 'bla',
    url: 'https://swapi.dev/api/planets/1/',
  },
  {
    name: 'bla10',
    diameter: 'bla',
    climate: 'bla',
    terrain: 'bla',
    population: 'bla',
    url: 'https://swapi.dev/api/planets/1/',
  },
];

export const details = {
  name: 'bla',
  rotation_period: 'bla',
  orbital_period: 'bla',
  diameter: 'bla',
  climate: 'bla',
  gravity: 'bla',
  terrain: 'bla',
  surface_water: 'bla',
  population: 'bla',
  url: 'https://swapi.dev/api/planets/1/',
};
